### ISSUE TITLE
dataset todos checklist

### ISSUE THREAD

**Issue by lucyWMDE** [codingdavinci/relaunch2018#118]
- [ ] fix those where the description text was cropped
- [ ] add back sounds to those that have them
- [ ] fix unklar licenses
- [ ] shorten long titles
